.PHONY: clean All

All:
	@echo "----------Building project:[ MergeSort - Debug ]----------"
	@cd "MergeSort" && $(MAKE) -f  "MergeSort.mk"
clean:
	@echo "----------Cleaning project:[ MergeSort - Debug ]----------"
	@cd "MergeSort" && $(MAKE) -f  "MergeSort.mk" clean
