.PHONY: clean All

All:
	@echo "----------Building project:[ BiTree - Debug ]----------"
	@cd "BiTree" && $(MAKE) -f  "BiTree.mk"
clean:
	@echo "----------Cleaning project:[ BiTree - Debug ]----------"
	@cd "BiTree" && $(MAKE) -f  "BiTree.mk" clean
